apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-5005-416-demo-python-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-5005-416-demo-python-3 
  name: sjm-5005-416-demo-python-3
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sjm-5005-416-demo-python-3
    weight: 100 
