apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-5005-416-demo-python-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-5005-416-demo-python-3 
  name: sjm-5005-416-demo-python-3
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjm-5005-416-demo-python-3 
